# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite_hamster_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='likes_cheese',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=b'First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Male'), (2, b'Female')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=b'Last Name', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_email',
            field=models.EmailField(default=b'@mail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_email',
            field=models.EmailField(default=b'@fulcrum.net', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
