# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 06:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20170324_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(help_text=b'Enter date in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joining_date',
            field=models.DateField(help_text=b'Enter date in YYYY-MM-DD format', null=True),
        ),
    ]
