# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20170324_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profimg',
            field=models.FileField(null=True, upload_to=b'profimg'),
        ),
    ]
