# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userprofile_profimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profimg',
            field=models.ImageField(null=True, upload_to=b'profimg'),
        ),
    ]
