# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20170324_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profimg',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b'avatar'),
        ),
    ]
